/* tslint:disable */
/* eslint-disable */
/**
 * 表单引擎API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface ColumnItem
 */
export interface ColumnItem {
    /**
     * 
     * @type {string}
     * @memberof ColumnItem
     */
    'key': string;
    /**
     * 
     * @type {string}
     * @memberof ColumnItem
     */
    'dataIndex': string;
    /**
     * 
     * @type {string}
     * @memberof ColumnItem
     */
    'type': string;
    /**
     * 
     * @type {string}
     * @memberof ColumnItem
     */
    'title': string;
    /**
     * 
     * @type {object}
     * @memberof ColumnItem
     */
    'label'?: object;
    /**
     * 
     * @type {object}
     * @memberof ColumnItem
     */
    'map'?: object;
    /**
     * 
     * @type {boolean}
     * @memberof ColumnItem
     */
    'disabled'?: boolean;
}

