/* tslint:disable */
/* eslint-disable */
/**
 * 表单引擎API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { ColumnItem } from './column-item';
import { FormEntity } from './form-entity';
import { RowItem } from './row-item';

/**
 * 
 * @export
 * @interface CommitListResEntity
 */
export interface CommitListResEntity {
    /**
     * 
     * @type {number}
     * @memberof CommitListResEntity
     */
    'total': number;
    /**
     * 
     * @type {FormEntity}
     * @memberof CommitListResEntity
     */
    'formEntity': FormEntity;
    /**
     * 
     * @type {Array<ColumnItem>}
     * @memberof CommitListResEntity
     */
    'columns': Array<ColumnItem>;
    /**
     * 
     * @type {Array<RowItem>}
     * @memberof CommitListResEntity
     */
    'rows': Array<RowItem>;
}

