/* tslint:disable */
/* eslint-disable */
/**
 * 表单引擎API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { FormDataProtocolClass } from './form-data-protocol-class';

/**
 * 
 * @export
 * @interface CreateFormEntityDto
 */
export interface CreateFormEntityDto {
    /**
     * 
     * @type {FormDataProtocolClass}
     * @memberof CreateFormEntityDto
     */
    'content': FormDataProtocolClass;
    /**
     * 
     * @type {number}
     * @memberof CreateFormEntityDto
     */
    'uid': number;
    /**
     * 
     * @type {string}
     * @memberof CreateFormEntityDto
     */
    'works_id': string;
    /**
     * 表单类型
     * @type {string}
     * @memberof CreateFormEntityDto
     */
    'type'?: string;
    /**
     * 表单模版来源
     * @type {string}
     * @memberof CreateFormEntityDto
     */
    'formTemplateId'?: string;
}

