/* tslint:disable */
/* eslint-disable */
/**
 * 表单引擎API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface CreateVoteFormDto
 */
export interface CreateVoteFormDto {
    /**
     * 
     * @type {string}
     * @memberof CreateVoteFormDto
     */
    'worksId': string;
    /**
     * 
     * @type {string}
     * @memberof CreateVoteFormDto
     */
    'uid': string;
    /**
     * 投票类型。文字投票 ｜ 图片投票
     * @type {object}
     * @memberof CreateVoteFormDto
     */
    'type': object;
}

