/* tslint:disable */
/* eslint-disable */
/**
 * 表单引擎API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface FormDataProtocolClass
 */
export interface FormDataProtocolClass {
    /**
     * 表单 id
     * @type {string}
     * @memberof FormDataProtocolClass
     */
    'formId'?: string;
    /**
     * 表单 name
     * @type {string}
     * @memberof FormDataProtocolClass
     */
    'formName'?: string;
    /**
     * 表单业务类型
     * @type {string}
     * @memberof FormDataProtocolClass
     */
    'type'?: string;
    /**
     * 描述
     * @type {string}
     * @memberof FormDataProtocolClass
     */
    'desc'?: string;
    /**
     * 字段
     * @type {Array<object>}
     * @memberof FormDataProtocolClass
     */
    'fields'?: Array<object>;
    /**
     * 提交规则
     * @type {boolean}
     * @memberof FormDataProtocolClass
     */
    'oneSubmissionPerPerson'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof FormDataProtocolClass
     */
    'isNeedCollectWechat'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof FormDataProtocolClass
     */
    'wechatSubmissionOnly'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof FormDataProtocolClass
     */
    'submissionMaxLimit'?: boolean;
    /**
     * 最大提交数
     * @type {number}
     * @memberof FormDataProtocolClass
     */
    'submissionMaxNum'?: number;
    /**
     * 
     * @type {boolean}
     * @memberof FormDataProtocolClass
     */
    'jumpAfterSubmission'?: boolean;
    /**
     * 
     * @type {string}
     * @memberof FormDataProtocolClass
     */
    'jumpLink'?: string;
    /**
     * 是否需要验证
     * @type {boolean}
     * @memberof FormDataProtocolClass
     */
    'needWXAuth'?: boolean;
    /**
     * 表单字体颜色
     * @type {string}
     * @memberof FormDataProtocolClass
     */
    'fontColor'?: string;
    /**
     * 控件颜色
     * @type {string}
     * @memberof FormDataProtocolClass
     */
    'controlColor'?: string;
    /**
     * 
     * @type {string}
     * @memberof FormDataProtocolClass
     */
    'btnText'?: string;
    /**
     * 
     * @type {string}
     * @memberof FormDataProtocolClass
     */
    'submitFeedback'?: string;
}

