/* tslint:disable */
/* eslint-disable */
/**
 * 表单引擎API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { FormDataProtocolClass } from './form-data-protocol-class';

/**
 * 
 * @export
 * @interface FormEntity
 */
export interface FormEntity {
    /**
     * 
     * @type {string}
     * @memberof FormEntity
     */
    'id': string;
    /**
     * 
     * @type {string}
     * @memberof FormEntity
     */
    'uid': string;
    /**
     * 
     * @type {string}
     * @memberof FormEntity
     */
    'works_id': string;
    /**
     * 
     * @type {string}
     * @memberof FormEntity
     */
    'form_template_ref': string;
    /**
     * 
     * @type {string}
     * @memberof FormEntity
     */
    'type': string;
    /**
     * 
     * @type {number}
     * @memberof FormEntity
     */
    'status': number;
    /**
     * 
     * @type {string}
     * @memberof FormEntity
     */
    'create_date': string;
    /**
     * 
     * @type {string}
     * @memberof FormEntity
     */
    'update_date': string;
    /**
     * 
     * @type {FormDataProtocolClass}
     * @memberof FormEntity
     */
    'content': FormDataProtocolClass;
}

