/* tslint:disable */
/* eslint-disable */
/**
 * 表单引擎API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface QueryFormEntityDto
 */
export interface QueryFormEntityDto {
    /**
     * 
     * @type {Array<string>}
     * @memberof QueryFormEntityDto
     */
    'worksIds': Array<string>;
    /**
     * 
     * @type {string}
     * @memberof QueryFormEntityDto
     */
    'type'?: string;
}

