/* tslint:disable */
/* eslint-disable */
/**
 * 表单引擎API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { SubmitFormDto } from './submit-form-dto';

/**
 * 
 * @export
 * @interface SubmitFormResEntity
 */
export interface SubmitFormResEntity {
    /**
     * 
     * @type {string}
     * @memberof SubmitFormResEntity
     */
    'formId': string;
    /**
     * 
     * @type {string}
     * @memberof SubmitFormResEntity
     */
    'commitId': string;
    /**
     * 
     * @type {SubmitFormDto}
     * @memberof SubmitFormResEntity
     */
    'submitFormData': SubmitFormDto;
}

