'use client';

import { onScreenShot } from '@/components/GridEditorV3/utils';
import ImageCropper from '@/components/ImageCropper';
import LibPicture from '@/components/LibPicture';
import { API, cdnApi, getAppId, getWorkData2, request, updateWorksDetail2 } from '@/services';
import APPBridge from '@/store/app-bridge';
import { getCookie } from '@/utils/cookie';
import { canUseRnChoosePic, showRnChoosePic } from '@/utils/rnChoosePic';
import { SerializedWorksEntity, trpc } from '@/utils/trpc';
import { Input } from '@workspace/ui/components/input';
import { Loading } from '@workspace/ui/components/loading';
import { ResponsiveDialog } from '@workspace/ui/components/responsive-dialog';
import { Textarea } from '@workspace/ui/components/textarea';
import dayjs from 'dayjs';
import zhCn from 'dayjs/locale/zh-cn';
import relativeTime from 'dayjs/plugin/relativeTime';
import { Pencil } from 'lucide-react';
import { useTranslations } from 'next-intl';
import { useEffect, useRef, useState } from 'react';
import toast from 'react-hot-toast';
import { useStore } from '../../store';
import { IWorksData } from '../GridEditorV3/works-store/types';

dayjs.extend(relativeTime);
dayjs.locale(zhCn);

interface WorkInfoCardProps {
  work: SerializedWorksEntity;
  purchaseStatus?: 'purchased' | 'not-purchased' | null;
  onClick?: () => void;
  loading?: boolean;
  onWorkUpdate?: (work: SerializedWorksEntity) => void;
}

export function WorkInfoCardEditable({
  work,
  onClick,
  loading = false,
  onWorkUpdate,
}: WorkInfoCardProps) {
  const t = useTranslations('WorkInfoCard');
  const tGrid = useTranslations('GridEditor');
  const resizeWidth = 192; // 96px * 2 for retina

  // 编辑相关状态
  const [showEditDialog, setShowEditDialog] = useState(false);
  const [editTitle, setEditTitle] = useState(work.title || '');
  const [editDesc, setEditDesc] = useState((work as any).desc || '');
  const [editCover, setEditCover] = useState(work.cover || '');
  const [generatingContent, setGeneratingContent] = useState(false);
  const [showCrop, setShowCrop] = useState(false);
  const [cropImageUrl, setCropImageUrl] = useState('');
  const [showPictureSelector, setShowPictureSelector] = useState(false);
  const inputRef = useRef<HTMLInputElement | null>(null);
  const hasAutoGeneratedRef = useRef(false); // 标记是否已经自动生成过
  const store = useStore();

  // 同步外部 work 数据到编辑状态
  useEffect(() => {
    setEditTitle(work.title || '');
    setEditDesc(work.desc || '');
    setEditCover(work.cover || '');
  }, [work]);

  // 初始化时自动生成标题和描述（如果 is_title_desc_modified === false）
  useEffect(() => {
    const autoGenerate = async () => {
      if (!work.id || hasAutoGeneratedRef.current) return;

      // 标记已执行，避免重复生成
      hasAutoGeneratedRef.current = true;

      try {
        // 获取作品数据
        const res = await getWorkData2(work.id);
        const detail = res?.detail;
        const worksData = res?.work_data;

        if (!detail) return;

        // 准备异步任务
        const tasks: Array<Promise<any>> = [];
        let needGeneration = false;

        // 检查是否需要生成封面（独立于标题描述的状态）
        if (!detail.cover || /gif/gi.test(detail.cover)) {
          console.log('[WorkInfoCard] 需要生成封面');
          needGeneration = true;
          tasks.push(generateScreenshot());
        }

        // 判断是否需要自动生成标题和描述（需要 worksData 且 is_title_desc_modified === false）
        if (worksData && !detail.is_title_desc_modified) {
          console.log('[WorkInfoCard] 需要生成标题和描述');
          needGeneration = true;
          tasks.push(generateMeta(worksData));
        }

        // 如果有需要生成的内容，显示 loading 并等待所有任务完成
        if (needGeneration && tasks.length) {
          setGeneratingContent(true);
          try {
            const results = await Promise.all(tasks);

            // 处理封面生成结果（先处理，因为可能没有标题描述生成）
            const screenshotResult = results.find(
              r => r && r.success && r.cover
            );
            if (screenshotResult && screenshotResult.cover) {
              setEditCover(screenshotResult.cover);
              if (onWorkUpdate) {
                const updatedWork = { ...work };
                updatedWork.cover = screenshotResult.cover;
                onWorkUpdate(updatedWork);
              }
            }

            // 处理标题描述生成结果
            const metaResult = results.find(r => r && r.title);
            if (metaResult && metaResult.title) {
              setEditTitle(metaResult.title);
              setEditDesc(metaResult.desc || '');
              console.log('[WorkInfoCard] 使用生成的标题:', metaResult.title);

              // 通知外部更新
              if (onWorkUpdate) {
                const updatedWork = { ...work };
                updatedWork.title = metaResult.title;
                updatedWork.desc = metaResult.desc || '';
                updatedWork.is_title_desc_modified = true;
                onWorkUpdate(updatedWork);
              }
            }
          } catch (error) {
            console.error('[WorkInfoCard] 生成内容时出错:', error);
          } finally {
            setGeneratingContent(false);
          }
        }
      } catch (error) {
        console.error('[WorkInfoCard] 自动生成失败:', error);
        setGeneratingContent(false);
      }
    };

    // 只在组件首次加载时执行一次
    autoGenerate();
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [work.id]);

  const handleClick = () => {
    if (!loading && onClick) {
      onClick();
    }
  };

  const handleEditClick = (e: React.MouseEvent) => {
    e.stopPropagation();
    setShowEditDialog(true);
  };

  // 生成截图的通用函数
  const generateScreenshot = async () => {
    try {
      const screenshotRes = await onScreenShot({
        id: work.id,
        width: 375,
        height: 375,
        appid: getAppId(),
      });
      const coverUrl = cdnApi(screenshotRes[0], {
        resizeWidth: 375,
        resizeHeight: 375,
      });
      setEditCover(coverUrl);
      await updateWorksDetail2(work.id, {
        cover: coverUrl,
      } as any);
      console.log('[WorkInfoCard] 截图生成成功:', coverUrl);
      return { success: true, cover: coverUrl };
    } catch (error) {
      console.error('[WorkInfoCard] 生成截图失败:', error);
      return { success: false };
    }
  };

  // 生成标题和描述的通用函数
  const generateMeta = async (worksData: IWorksData) => {
    try {
      const layers = worksData.layersMap;
      let workText = '';

      Object.values(layers).forEach(layer => {
        if (layer.elementRef === 'Text' && layer.attrs?.text) {
          workText += layer.attrs.text + ' ';
        }
      });

      workText = workText.trim();

      if (!workText) {
        console.log('[WorkInfoCard] 未找到文本内容，使用默认标题');
        return {
          success: false,
          title: t('我的作品'),
          desc: t('欢迎查看'),
        };
      }

      console.log('[WorkInfoCard] 提取的文本长度:', workText.length);

      const useV11API = typeof process !== 'undefined' && process.env.APIV11 === 'true';

      let metaRes: { title?: string; desc?: string } | undefined;

      if (useV11API) {
        // 使用 tRPC 调用火山引擎 ARK API，按当前语言生成标题描述
        const currentLocale = getCookie('NEXT_LOCALE') || 'zh-CN';
        metaRes = await trpc.aiGenerate.generateWorkMeta.mutate({
          workText: workText.slice(0, 500),
          language: currentLocale,
        });
      } else {
        metaRes = await request.post(
          `${API('apiv10')}/ai-generate/work-meta`,
          {
            workText: workText.slice(0, 500),
          }
        );
      }

      if (metaRes && metaRes.title && metaRes.desc) {
        console.log('[WorkInfoCard] AI生成结果:', {
          title: metaRes.title,
          desc: metaRes.desc,
        });

        // 保存生成的标题和描述
        await updateWorksDetail2(work.id, {
          title: metaRes.title,
          desc: metaRes.desc,
          is_title_desc_modified: true,
        });

        setEditTitle(metaRes.title);
        setEditDesc(metaRes.desc);

        console.log(
          '[WorkInfoCard] 标题描述已保存，is_title_desc_modified 设置为 true'
        );

        return {
          success: true,
          title: metaRes.title,
          desc: metaRes.desc,
        };
      } else {
        console.warn('[WorkInfoCard] AI 返回结果格式不正确:', metaRes);
        return {
          success: false,
          title: t('我的作品'),
          desc: workText.slice(0, 60),
        };
      }
    } catch (error) {
      console.error('[WorkInfoCard] 生成标题描述失败:', error);
      return {
        success: false,
        title: t('我的作品'),
        desc: t('欢迎查看'),
      };
    }
  };

  // 点击"重新生成"按钮强制重新生成
  const regenerateContent = async () => {
    if (!work.id) {
      toast.error(t('缺少作品ID'));
      return;
    }

    setGeneratingContent(true);

    try {
      const res = await getWorkData2(work.id);
      const worksData = res?.work_data;

      if (!worksData) {
        toast.error(t('未找到作品数据'));
        return;
      }

      // 并行生成截图和标题描述
      const [screenshotResult, metaResult] = await Promise.all([
        generateScreenshot(),
        generateMeta(worksData),
      ]);

      // 更新界面标题和描述
      if (metaResult && metaResult.title) {
        setEditTitle(metaResult.title);
        setEditDesc(metaResult.desc || '');
      }

      if (screenshotResult?.success || metaResult?.success) {
        toast.success(t('生成完成'));
        // 通知外部更新
        if (onWorkUpdate) {
          const updatedWork = { ...work };
          if (screenshotResult?.cover) {
            updatedWork.cover = screenshotResult.cover;
          }
          if (metaResult?.title) {
            updatedWork.title = metaResult.title;
            (updatedWork as any).desc = metaResult.desc || '';
          }
          onWorkUpdate(updatedWork);
        }
      } else {
        toast.error(t('生成失败，请重试'));
      }
    } catch (error) {
      console.error('[WorkInfoCard] 重新生成内容失败:', error);
      toast.error(t('生成失败，请重试'));
    } finally {
      setGeneratingContent(false);
    }
  };

  // 更新标题
  const updateTitle = async (title: string) => {
    try {
      await updateWorksDetail2(work.id, {
        title,
        is_title_desc_modified: true,
      } as any);
      if (onWorkUpdate) {
        const updatedWork = { ...work, title };
        onWorkUpdate(updatedWork);
      }
    } catch (error) {
      console.error('更新标题失败:', error);
      toast.error(t('更新标题失败'));
    }
  };

  // 更新描述
  const updateDesc = async (desc: string) => {
    try {
      await updateWorksDetail2(work.id, {
        desc,
        is_title_desc_modified: true,
      } as any);
      if (onWorkUpdate) {
        const updatedWork = { ...work };
        (updatedWork as any).desc = desc;
        onWorkUpdate(updatedWork);
      }
    } catch (error) {
      console.error('更新描述失败:', error);
      toast.error(t('更新描述失败'));
    }
  };

  // 处理封面上传
  const onChangeUpload = async (e: React.ChangeEvent<HTMLInputElement>) => {
    const maxSize = 50;
    let files = e.target.files;
    if (files?.length) {
      const file = files[0];
      if ((file as File).size * 0.001 > maxSize * 1024) {
        toast.error(t('文件不能超过{size}mb', { size: maxSize }));
        return;
      }
      setCropImageUrl(URL.createObjectURL(file));
      setShowCrop(true);
    }
  };

  // 处理封面裁剪完成
  const handleCoverChange = async (url: string) => {
    setEditCover(url);
    await updateWorksDetail2(work.id, {
      cover: url,
    } as any);
    if (onWorkUpdate) {
      const updatedWork = { ...work, cover: url };
      onWorkUpdate(updatedWork);
    }
    setShowCrop(false);
  };

  return (
    <>
      <div
        onClick={handleClick}
        className={`relative ${onClick && !loading
          ? 'cursor-pointer'
          : loading
            ? 'cursor-wait opacity-60'
            : ''
          }`}
      >
        <div className='flex gap-2 items-start'>
          {/* 缩略图 */}
          <div className='w-[72px] h-[72px] relative flex-shrink-0 overflow-hidden rounded-[14px] bg-slate-100 border border-slate-100 shadow-sm'>
            {work.cover ? (
              // eslint-disable-next-line @next/next/no-img-element
              <img
                src={cdnApi(work.cover, { resizeWidth })}
                alt={work.title}
                className='w-full h-full object-cover'
              />
            ) : (
              <div className='w-full h-full flex flex-col items-center justify-center text-gray-400'>
                <div className='text-[24px] mb-1'>🖼️</div>
              </div>
            )}
            {/* 加载蒙层 */}
            {loading && (
              <div className='absolute inset-0 bg-black bg-opacity-30 flex items-center justify-center'>
                <div className='w-6 h-6 border-2 border-white border-t-transparent rounded-full animate-spin' />
              </div>
            )}
          </div>

          {/* 内容 */}
          <div className='flex-1 min-w-0 pt-0.5 relative'>
            <div className='flex items-start justify-between mb-1'>
              <h3 className='text-base font-semibold leading-6 text-[#0f172b] pr-8'>
                {work.title}
              </h3>
              {/* 编辑按钮 */}
              <button
                className='absolute top-0 right-0 w-[30px] h-[30px] flex items-center justify-center rounded-full hover:bg-slate-100 transition-colors'
                onClick={e => {
                  e.stopPropagation();
                  setShowEditDialog(true);
                }}
              >
                <Pencil className='w-[18px] h-[18px] text-[#64748b]' />
              </button>
            </div>
            {/* 描述 */}
            {(work as any).desc && (
              <p className='text-sm leading-5 text-[#62748e] line-clamp-1 mb-1'>
                {(work as any).desc}
              </p>
            )}
          </div>
        </div>
      </div>

      {/* 编辑弹窗 */}
      <ResponsiveDialog
        isOpen={showEditDialog}
        onOpenChange={setShowEditDialog}
        handleOnly={true}
        title={t('编辑标题、描述和封面')}
        isDialog
      >
        <div className='p-4 space-y-3'>
          <div className='flex items-center justify-between'>
            <p className='text-xs font-semibold text-[#64748B] leading-[18px]'>
              {t('编辑标题、描述和封面')}
            </p>
            <div
              className='px-2 py-0.5 rounded cursor-pointer hover:bg-[#EEF2FF] transition-colors'
              onClick={regenerateContent}
            >
              <p className='text-xs font-semibold text-[#3358D4] leading-[18px]'>
                {t('重新生成')}
              </p>
            </div>
          </div>

          {/* 标题输入 */}
          <div className='relative'>
            <Input
              value={editTitle}
              onChange={e => setEditTitle(e.target.value)}
              onBlur={() => updateTitle(editTitle)}
              className='w-full bg-white border-[#C1D0FF] rounded-md px-3 py-2 text-sm font-semibold text-[rgba(0,0,0,0.88)] leading-5 pr-14'
              placeholder={t('请输入标题')}
              maxLength={36}
            />
            <div className='absolute right-3 top-1/2 -translate-y-1/2 text-xs text-[#020617] leading-[18px]'>
              {editTitle.length}/36
            </div>
          </div>

          {/* 封面和描述 */}
          <div className='flex gap-2'>
            {/* 封面 */}
            <div className='relative flex-shrink-0'>
              <input
                className='hidden'
                ref={inputRef}
                onChange={onChangeUpload}
                type='file'
                accept='image/*'
                multiple={false}
                title='封面上传'
              />
              <div className='w-24 h-24 rounded-md bg-gray-200 overflow-hidden'>
                {editCover ? (
                  <img
                    src={cdnApi(editCover)}
                    alt='封面'
                    className='w-full h-full object-cover'
                  />
                ) : (
                  <div className='w-full h-full flex items-center justify-center text-xs text-gray-400'>
                    {t('封面')}
                  </div>
                )}
              </div>
              <div
                className='absolute bottom-0 left-0 right-0 bg-black/60 text-white text-xs text-center py-1 rounded-b-md cursor-pointer'
                onClick={async () => {
                  if (await canUseRnChoosePic()) {
                    showRnChoosePic((url?: string) => {
                      if (url) {
                        setCropImageUrl(url);
                        setShowCrop(true);
                      }
                    }, tGrid);
                  } else if (APPBridge.judgeIsInApp()) {
                    setShowPictureSelector(true);
                  } else {
                    inputRef.current?.click();
                  }
                }}
              >
                {t('更换封面')}
              </div>
            </div>

            {/* 描述 */}
            <div className='flex-1 relative'>
              <Textarea
                value={editDesc}
                onChange={e => setEditDesc(e.target.value)}
                onBlur={() => updateDesc(editDesc)}
                className='w-full bg-white border-[#C1D0FF] rounded-md px-3 py-2 text-xs text-[rgba(0,0,0,0.88)] leading-[18px] min-h-[96px] resize-none'
                placeholder={t('请输入描述')}
                maxLength={60}
              />
              <div className='absolute bottom-2 right-3 text-xs text-[#020617] leading-[18px]'>
                {editDesc.length}/60
              </div>
            </div>
          </div>
        </div>
      </ResponsiveDialog>

      {/* 封面裁剪弹窗 */}
      <ResponsiveDialog
        isOpen={showCrop}
        onOpenChange={setShowCrop}
        handleOnly={true}
      >
        <ImageCropper
          worksId={work.id}
          imageUrl={cropImageUrl}
          onClose={() => setShowCrop(false)}
          onChange={handleCoverChange}
        />
      </ResponsiveDialog>

      {/* 图片选择弹窗 */}
      <ResponsiveDialog
        isOpen={showPictureSelector}
        onOpenChange={setShowPictureSelector}
        title={t('更换封面')}
        contentProps={{
          className: 'pt-2',
        }}
      >
        <LibPicture
          preUpload={false}
          onSelectItem={(url: string) => {
            setCropImageUrl(url);
            setShowCrop(true);
            setShowPictureSelector(false);
          }}
        />
      </ResponsiveDialog>

      {/* 生成中提示弹窗 */}
      <ResponsiveDialog
        isOpen={generatingContent}
        isDialog
        contentProps={{
          className: 'max-w-[320px]',
        }}
      >
        <div className='p-4 flex flex-col items-center gap-2 mx-2 max-w-[320px]'>
          <Loading />
          <div className=''>{t('请稍等，标题和封面自动生成中')}</div>
        </div>
      </ResponsiveDialog>
    </>
  );
}
