/* tslint:disable */
/* eslint-disable */
/**
 * 表单引擎API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import globalAxios, { AxiosPromise, AxiosInstance, AxiosRequestConfig } from 'axios';
import { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
/**
 * DatiApi - axios parameter creator
 * @export
 */
export const DatiApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @param {string} formId 
         * @param {number} page 
         * @param {number} limit 
         * @param {string} noCache 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getDatiList: async (formId: string, page: number, limit: number, noCache: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'formId' is not null or undefined
            assertParamExists('getDatiList', 'formId', formId)
            // verify required parameter 'page' is not null or undefined
            assertParamExists('getDatiList', 'page', page)
            // verify required parameter 'limit' is not null or undefined
            assertParamExists('getDatiList', 'limit', limit)
            // verify required parameter 'noCache' is not null or undefined
            assertParamExists('getDatiList', 'noCache', noCache)
            const localVarPath = `/dati/v1/rank/{formId}`
                .replace(`{${"formId"}}`, encodeURIComponent(String(formId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (page !== undefined) {
                localVarQueryParameter['page'] = page;
            }

            if (limit !== undefined) {
                localVarQueryParameter['limit'] = limit;
            }

            if (noCache !== undefined) {
                localVarQueryParameter['noCache'] = noCache;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 测试接口，不使用缓存
         * @summary 
         * @param {string} formId 
         * @param {string} openId 
         * @param {string} noCache 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getUserRank: async (formId: string, openId: string, noCache: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'formId' is not null or undefined
            assertParamExists('getUserRank', 'formId', formId)
            // verify required parameter 'openId' is not null or undefined
            assertParamExists('getUserRank', 'openId', openId)
            // verify required parameter 'noCache' is not null or undefined
            assertParamExists('getUserRank', 'noCache', noCache)
            const localVarPath = `/dati/v1/user/rank/{formId}/{openId}`
                .replace(`{${"formId"}}`, encodeURIComponent(String(formId)))
                .replace(`{${"openId"}}`, encodeURIComponent(String(openId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (noCache !== undefined) {
                localVarQueryParameter['noCache'] = noCache;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * DatiApi - functional programming interface
 * @export
 */
export const DatiApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = DatiApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @param {string} formId 
         * @param {number} page 
         * @param {number} limit 
         * @param {string} noCache 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getDatiList(formId: string, page: number, limit: number, noCache: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<object>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getDatiList(formId, page, limit, noCache, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 测试接口，不使用缓存
         * @summary 
         * @param {string} formId 
         * @param {string} openId 
         * @param {string} noCache 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getUserRank(formId: string, openId: string, noCache: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<object>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getUserRank(formId, openId, noCache, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
    }
};

/**
 * DatiApi - factory interface
 * @export
 */
export const DatiApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = DatiApiFp(configuration)
    return {
        /**
         * 
         * @param {string} formId 
         * @param {number} page 
         * @param {number} limit 
         * @param {string} noCache 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getDatiList(formId: string, page: number, limit: number, noCache: string, options?: any): AxiosPromise<object> {
            return localVarFp.getDatiList(formId, page, limit, noCache, options).then((request) => request(axios, basePath));
        },
        /**
         * 测试接口，不使用缓存
         * @summary 
         * @param {string} formId 
         * @param {string} openId 
         * @param {string} noCache 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getUserRank(formId: string, openId: string, noCache: string, options?: any): AxiosPromise<object> {
            return localVarFp.getUserRank(formId, openId, noCache, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * DatiApi - object-oriented interface
 * @export
 * @class DatiApi
 * @extends {BaseAPI}
 */
export class DatiApi extends BaseAPI {
    /**
     * 
     * @param {string} formId 
     * @param {number} page 
     * @param {number} limit 
     * @param {string} noCache 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DatiApi
     */
    public getDatiList(formId: string, page: number, limit: number, noCache: string, options?: AxiosRequestConfig) {
        return DatiApiFp(this.configuration).getDatiList(formId, page, limit, noCache, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 测试接口，不使用缓存
     * @summary 
     * @param {string} formId 
     * @param {string} openId 
     * @param {string} noCache 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DatiApi
     */
    public getUserRank(formId: string, openId: string, noCache: string, options?: AxiosRequestConfig) {
        return DatiApiFp(this.configuration).getUserRank(formId, openId, noCache, options).then((request) => request(this.axios, this.basePath));
    }
}
