/* tslint:disable */
/* eslint-disable */
/**
 * 表单引擎API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import globalAxios, { AxiosPromise, AxiosInstance, AxiosRequestConfig } from 'axios';
import { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
// @ts-ignore
import { CommitListResEntity } from '../models';
// @ts-ignore
import { CountFormEntity } from '../models';
// @ts-ignore
import { DeleteSubmitFormDto } from '../models';
// @ts-ignore
import { ListCommitDataDto } from '../models';
// @ts-ignore
import { SubmitFormDto } from '../models';
// @ts-ignore
import { SubmitFormResEntity } from '../models';
/**
 * FormReceiverServicesApi - axios parameter creator
 * @export
 */
export const FormReceiverServicesApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @param {string} formId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        countForm: async (formId: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'formId' is not null or undefined
            assertParamExists('countForm', 'formId', formId)
            const localVarPath = `/form-receiver/v1/count/{formId}`
                .replace(`{${"formId"}}`, encodeURIComponent(String(formId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} formId 
         * @param {DeleteSubmitFormDto} deleteSubmitFormDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteSubmitData: async (formId: string, deleteSubmitFormDto: DeleteSubmitFormDto, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'formId' is not null or undefined
            assertParamExists('deleteSubmitData', 'formId', formId)
            // verify required parameter 'deleteSubmitFormDto' is not null or undefined
            assertParamExists('deleteSubmitData', 'deleteSubmitFormDto', deleteSubmitFormDto)
            const localVarPath = `/form-receiver/v1/form-submit/delete/{formId}`
                .replace(`{${"formId"}}`, encodeURIComponent(String(formId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(deleteSubmitFormDto, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} formId 
         * @param {SubmitFormDto} submitFormDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        formSubmit: async (formId: string, submitFormDto: SubmitFormDto, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'formId' is not null or undefined
            assertParamExists('formSubmit', 'formId', formId)
            // verify required parameter 'submitFormDto' is not null or undefined
            assertParamExists('formSubmit', 'submitFormDto', submitFormDto)
            const localVarPath = `/form-receiver/v1/form-submit/{formId}`
                .replace(`{${"formId"}}`, encodeURIComponent(String(formId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(submitFormDto, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} formId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getFormList: async (formId: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'formId' is not null or undefined
            assertParamExists('getFormList', 'formId', formId)
            const localVarPath = `/form-receiver/v1/list/{formId}`
                .replace(`{${"formId"}}`, encodeURIComponent(String(formId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} formId 
         * @param {ListCommitDataDto} listCommitDataDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getFormListByCommitIds: async (formId: string, listCommitDataDto: ListCommitDataDto, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'formId' is not null or undefined
            assertParamExists('getFormListByCommitIds', 'formId', formId)
            // verify required parameter 'listCommitDataDto' is not null or undefined
            assertParamExists('getFormListByCommitIds', 'listCommitDataDto', listCommitDataDto)
            const localVarPath = `/form-receiver/v1/list/{formId}`
                .replace(`{${"formId"}}`, encodeURIComponent(String(formId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(listCommitDataDto, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} formId 
         * @param {ListCommitDataDto} listCommitDataDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getFormListByScope: async (formId: string, listCommitDataDto: ListCommitDataDto, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'formId' is not null or undefined
            assertParamExists('getFormListByScope', 'formId', formId)
            // verify required parameter 'listCommitDataDto' is not null or undefined
            assertParamExists('getFormListByScope', 'listCommitDataDto', listCommitDataDto)
            const localVarPath = `/form-receiver/v1/scope/list/{formId}`
                .replace(`{${"formId"}}`, encodeURIComponent(String(formId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(listCommitDataDto, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * FormReceiverServicesApi - functional programming interface
 * @export
 */
export const FormReceiverServicesApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = FormReceiverServicesApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @param {string} formId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async countForm(formId: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<CountFormEntity>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.countForm(formId, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @param {string} formId 
         * @param {DeleteSubmitFormDto} deleteSubmitFormDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async deleteSubmitData(formId: string, deleteSubmitFormDto: DeleteSubmitFormDto, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<string>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.deleteSubmitData(formId, deleteSubmitFormDto, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @param {string} formId 
         * @param {SubmitFormDto} submitFormDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async formSubmit(formId: string, submitFormDto: SubmitFormDto, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<SubmitFormResEntity>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.formSubmit(formId, submitFormDto, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @param {string} formId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getFormList(formId: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<CommitListResEntity>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getFormList(formId, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @param {string} formId 
         * @param {ListCommitDataDto} listCommitDataDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getFormListByCommitIds(formId: string, listCommitDataDto: ListCommitDataDto, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<CommitListResEntity>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getFormListByCommitIds(formId, listCommitDataDto, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @param {string} formId 
         * @param {ListCommitDataDto} listCommitDataDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getFormListByScope(formId: string, listCommitDataDto: ListCommitDataDto, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<CommitListResEntity>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getFormListByScope(formId, listCommitDataDto, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
    }
};

/**
 * FormReceiverServicesApi - factory interface
 * @export
 */
export const FormReceiverServicesApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = FormReceiverServicesApiFp(configuration)
    return {
        /**
         * 
         * @param {string} formId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        countForm(formId: string, options?: any): AxiosPromise<CountFormEntity> {
            return localVarFp.countForm(formId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {string} formId 
         * @param {DeleteSubmitFormDto} deleteSubmitFormDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteSubmitData(formId: string, deleteSubmitFormDto: DeleteSubmitFormDto, options?: any): AxiosPromise<string> {
            return localVarFp.deleteSubmitData(formId, deleteSubmitFormDto, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {string} formId 
         * @param {SubmitFormDto} submitFormDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        formSubmit(formId: string, submitFormDto: SubmitFormDto, options?: any): AxiosPromise<SubmitFormResEntity> {
            return localVarFp.formSubmit(formId, submitFormDto, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {string} formId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getFormList(formId: string, options?: any): AxiosPromise<CommitListResEntity> {
            return localVarFp.getFormList(formId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {string} formId 
         * @param {ListCommitDataDto} listCommitDataDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getFormListByCommitIds(formId: string, listCommitDataDto: ListCommitDataDto, options?: any): AxiosPromise<CommitListResEntity> {
            return localVarFp.getFormListByCommitIds(formId, listCommitDataDto, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {string} formId 
         * @param {ListCommitDataDto} listCommitDataDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getFormListByScope(formId: string, listCommitDataDto: ListCommitDataDto, options?: any): AxiosPromise<CommitListResEntity> {
            return localVarFp.getFormListByScope(formId, listCommitDataDto, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * FormReceiverServicesApi - object-oriented interface
 * @export
 * @class FormReceiverServicesApi
 * @extends {BaseAPI}
 */
export class FormReceiverServicesApi extends BaseAPI {
    /**
     * 
     * @param {string} formId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof FormReceiverServicesApi
     */
    public countForm(formId: string, options?: AxiosRequestConfig) {
        return FormReceiverServicesApiFp(this.configuration).countForm(formId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {string} formId 
     * @param {DeleteSubmitFormDto} deleteSubmitFormDto 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof FormReceiverServicesApi
     */
    public deleteSubmitData(formId: string, deleteSubmitFormDto: DeleteSubmitFormDto, options?: AxiosRequestConfig) {
        return FormReceiverServicesApiFp(this.configuration).deleteSubmitData(formId, deleteSubmitFormDto, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {string} formId 
     * @param {SubmitFormDto} submitFormDto 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof FormReceiverServicesApi
     */
    public formSubmit(formId: string, submitFormDto: SubmitFormDto, options?: AxiosRequestConfig) {
        return FormReceiverServicesApiFp(this.configuration).formSubmit(formId, submitFormDto, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {string} formId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof FormReceiverServicesApi
     */
    public getFormList(formId: string, options?: AxiosRequestConfig) {
        return FormReceiverServicesApiFp(this.configuration).getFormList(formId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {string} formId 
     * @param {ListCommitDataDto} listCommitDataDto 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof FormReceiverServicesApi
     */
    public getFormListByCommitIds(formId: string, listCommitDataDto: ListCommitDataDto, options?: AxiosRequestConfig) {
        return FormReceiverServicesApiFp(this.configuration).getFormListByCommitIds(formId, listCommitDataDto, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {string} formId 
     * @param {ListCommitDataDto} listCommitDataDto 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof FormReceiverServicesApi
     */
    public getFormListByScope(formId: string, listCommitDataDto: ListCommitDataDto, options?: AxiosRequestConfig) {
        return FormReceiverServicesApiFp(this.configuration).getFormListByScope(formId, listCommitDataDto, options).then((request) => request(this.axios, this.basePath));
    }
}
