/* tslint:disable */
/* eslint-disable */
/**
 * 表单引擎API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import globalAxios, { AxiosPromise, AxiosInstance, AxiosRequestConfig } from 'axios';
import { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
// @ts-ignore
import { DailyReportResEntity } from '../models';
// @ts-ignore
import { ListCommitDataDto } from '../models';
// @ts-ignore
import { QueryFormEntityDto } from '../models';
/**
 * FormReportServicesApi - axios parameter creator
 * @export
 */
export const FormReportServicesApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        appDailyReport: async (options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/form-report/v1/app-daily-report/{worksId}`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {QueryFormEntityDto} queryFormEntityDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        countFormByWorksIds: async (queryFormEntityDto: QueryFormEntityDto, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'queryFormEntityDto' is not null or undefined
            assertParamExists('countFormByWorksIds', 'queryFormEntityDto', queryFormEntityDto)
            const localVarPath = `/form-report/v1/count-form-by-works-ids`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(queryFormEntityDto, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        exportSubmitData: async (options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/form-report/v1/export-submit-data/{formId}`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {ListCommitDataDto} listCommitDataDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        exportSubmitDataByCommitIds: async (listCommitDataDto: ListCommitDataDto, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'listCommitDataDto' is not null or undefined
            assertParamExists('exportSubmitDataByCommitIds', 'listCommitDataDto', listCommitDataDto)
            const localVarPath = `/form-report/v1/export-submit-data/{formId}`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(listCommitDataDto, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * FormReportServicesApi - functional programming interface
 * @export
 */
export const FormReportServicesApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = FormReportServicesApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async appDailyReport(options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<DailyReportResEntity>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.appDailyReport(options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @param {QueryFormEntityDto} queryFormEntityDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async countFormByWorksIds(queryFormEntityDto: QueryFormEntityDto, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<object>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.countFormByWorksIds(queryFormEntityDto, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async exportSubmitData(options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.exportSubmitData(options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @param {ListCommitDataDto} listCommitDataDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async exportSubmitDataByCommitIds(listCommitDataDto: ListCommitDataDto, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.exportSubmitDataByCommitIds(listCommitDataDto, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
    }
};

/**
 * FormReportServicesApi - factory interface
 * @export
 */
export const FormReportServicesApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = FormReportServicesApiFp(configuration)
    return {
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        appDailyReport(options?: any): AxiosPromise<DailyReportResEntity> {
            return localVarFp.appDailyReport(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {QueryFormEntityDto} queryFormEntityDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        countFormByWorksIds(queryFormEntityDto: QueryFormEntityDto, options?: any): AxiosPromise<object> {
            return localVarFp.countFormByWorksIds(queryFormEntityDto, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        exportSubmitData(options?: any): AxiosPromise<void> {
            return localVarFp.exportSubmitData(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {ListCommitDataDto} listCommitDataDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        exportSubmitDataByCommitIds(listCommitDataDto: ListCommitDataDto, options?: any): AxiosPromise<void> {
            return localVarFp.exportSubmitDataByCommitIds(listCommitDataDto, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * FormReportServicesApi - object-oriented interface
 * @export
 * @class FormReportServicesApi
 * @extends {BaseAPI}
 */
export class FormReportServicesApi extends BaseAPI {
    /**
     * 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof FormReportServicesApi
     */
    public appDailyReport(options?: AxiosRequestConfig) {
        return FormReportServicesApiFp(this.configuration).appDailyReport(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {QueryFormEntityDto} queryFormEntityDto 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof FormReportServicesApi
     */
    public countFormByWorksIds(queryFormEntityDto: QueryFormEntityDto, options?: AxiosRequestConfig) {
        return FormReportServicesApiFp(this.configuration).countFormByWorksIds(queryFormEntityDto, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof FormReportServicesApi
     */
    public exportSubmitData(options?: AxiosRequestConfig) {
        return FormReportServicesApiFp(this.configuration).exportSubmitData(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {ListCommitDataDto} listCommitDataDto 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof FormReportServicesApi
     */
    public exportSubmitDataByCommitIds(listCommitDataDto: ListCommitDataDto, options?: AxiosRequestConfig) {
        return FormReportServicesApiFp(this.configuration).exportSubmitDataByCommitIds(listCommitDataDto, options).then((request) => request(this.axios, this.basePath));
    }
}
