/* tslint:disable */
/* eslint-disable */
/**
 * 表单引擎API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import globalAxios, { AxiosPromise, AxiosInstance, AxiosRequestConfig } from 'axios';
import { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
// @ts-ignore
import { CreateFormEntityDto } from '../models';
// @ts-ignore
import { CreateFormResEntity } from '../models';
// @ts-ignore
import { FormEntity } from '../models';
// @ts-ignore
import { ListFormResEntity } from '../models';
// @ts-ignore
import { UpdateFormEntityDto } from '../models';
/**
 * FormEntityServicesApi - axios parameter creator
 * @export
 */
export const FormEntityServicesApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 创建表单
         * @summary 
         * @param {CreateFormEntityDto} createFormEntityDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        create: async (createFormEntityDto: CreateFormEntityDto, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'createFormEntityDto' is not null or undefined
            assertParamExists('create', 'createFormEntityDto', createFormEntityDto)
            const localVarPath = `/form-entity`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(createFormEntityDto, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 匿名创建表单
         * @summary 
         * @param {CreateFormEntityDto} createFormEntityDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createByAnonymous: async (createFormEntityDto: CreateFormEntityDto, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'createFormEntityDto' is not null or undefined
            assertParamExists('createByAnonymous', 'createFormEntityDto', createFormEntityDto)
            const localVarPath = `/form-entity/anonymous`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(createFormEntityDto, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 列出表单实体（有分页）
         * @summary 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        findAll: async (options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/form-entity`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 作品 id 范围下列出表单实体（有分页）
         * @summary 
         * @param {string} worksId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        findByWorksId: async (worksId: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'worksId' is not null or undefined
            assertParamExists('findByWorksId', 'worksId', worksId)
            const localVarPath = `/form-entity/from-works-id/{worksId}`
                .replace(`{${"worksId"}}`, encodeURIComponent(String(worksId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 找到表单实体
         * @summary 
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        findOne: async (id: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('findOne', 'id', id)
            const localVarPath = `/form-entity/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 删除表单实体
         * @summary 
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        remove: async (id: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('remove', 'id', id)
            const localVarPath = `/form-entity/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 更新表单实体
         * @summary 
         * @param {string} id 
         * @param {UpdateFormEntityDto} updateFormEntityDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        update: async (id: string, updateFormEntityDto: UpdateFormEntityDto, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('update', 'id', id)
            // verify required parameter 'updateFormEntityDto' is not null or undefined
            assertParamExists('update', 'updateFormEntityDto', updateFormEntityDto)
            const localVarPath = `/form-entity/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(updateFormEntityDto, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * FormEntityServicesApi - functional programming interface
 * @export
 */
export const FormEntityServicesApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = FormEntityServicesApiAxiosParamCreator(configuration)
    return {
        /**
         * 创建表单
         * @summary 
         * @param {CreateFormEntityDto} createFormEntityDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async create(createFormEntityDto: CreateFormEntityDto, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<CreateFormResEntity>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.create(createFormEntityDto, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 匿名创建表单
         * @summary 
         * @param {CreateFormEntityDto} createFormEntityDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async createByAnonymous(createFormEntityDto: CreateFormEntityDto, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<CreateFormResEntity>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.createByAnonymous(createFormEntityDto, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 列出表单实体（有分页）
         * @summary 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async findAll(options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<FormEntity>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.findAll(options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 作品 id 范围下列出表单实体（有分页）
         * @summary 
         * @param {string} worksId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async findByWorksId(worksId: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ListFormResEntity>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.findByWorksId(worksId, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 找到表单实体
         * @summary 
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async findOne(id: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<FormEntity>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.findOne(id, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 删除表单实体
         * @summary 
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async remove(id: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<string>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.remove(id, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 更新表单实体
         * @summary 
         * @param {string} id 
         * @param {UpdateFormEntityDto} updateFormEntityDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async update(id: string, updateFormEntityDto: UpdateFormEntityDto, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<string>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.update(id, updateFormEntityDto, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
    }
};

/**
 * FormEntityServicesApi - factory interface
 * @export
 */
export const FormEntityServicesApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = FormEntityServicesApiFp(configuration)
    return {
        /**
         * 创建表单
         * @summary 
         * @param {CreateFormEntityDto} createFormEntityDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        create(createFormEntityDto: CreateFormEntityDto, options?: any): AxiosPromise<CreateFormResEntity> {
            return localVarFp.create(createFormEntityDto, options).then((request) => request(axios, basePath));
        },
        /**
         * 匿名创建表单
         * @summary 
         * @param {CreateFormEntityDto} createFormEntityDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createByAnonymous(createFormEntityDto: CreateFormEntityDto, options?: any): AxiosPromise<CreateFormResEntity> {
            return localVarFp.createByAnonymous(createFormEntityDto, options).then((request) => request(axios, basePath));
        },
        /**
         * 列出表单实体（有分页）
         * @summary 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        findAll(options?: any): AxiosPromise<Array<FormEntity>> {
            return localVarFp.findAll(options).then((request) => request(axios, basePath));
        },
        /**
         * 作品 id 范围下列出表单实体（有分页）
         * @summary 
         * @param {string} worksId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        findByWorksId(worksId: string, options?: any): AxiosPromise<ListFormResEntity> {
            return localVarFp.findByWorksId(worksId, options).then((request) => request(axios, basePath));
        },
        /**
         * 找到表单实体
         * @summary 
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        findOne(id: string, options?: any): AxiosPromise<FormEntity> {
            return localVarFp.findOne(id, options).then((request) => request(axios, basePath));
        },
        /**
         * 删除表单实体
         * @summary 
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        remove(id: string, options?: any): AxiosPromise<string> {
            return localVarFp.remove(id, options).then((request) => request(axios, basePath));
        },
        /**
         * 更新表单实体
         * @summary 
         * @param {string} id 
         * @param {UpdateFormEntityDto} updateFormEntityDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        update(id: string, updateFormEntityDto: UpdateFormEntityDto, options?: any): AxiosPromise<string> {
            return localVarFp.update(id, updateFormEntityDto, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * FormEntityServicesApi - object-oriented interface
 * @export
 * @class FormEntityServicesApi
 * @extends {BaseAPI}
 */
export class FormEntityServicesApi extends BaseAPI {
    /**
     * 创建表单
     * @summary 
     * @param {CreateFormEntityDto} createFormEntityDto 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof FormEntityServicesApi
     */
    public create(createFormEntityDto: CreateFormEntityDto, options?: AxiosRequestConfig) {
        return FormEntityServicesApiFp(this.configuration).create(createFormEntityDto, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 匿名创建表单
     * @summary 
     * @param {CreateFormEntityDto} createFormEntityDto 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof FormEntityServicesApi
     */
    public createByAnonymous(createFormEntityDto: CreateFormEntityDto, options?: AxiosRequestConfig) {
        return FormEntityServicesApiFp(this.configuration).createByAnonymous(createFormEntityDto, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 列出表单实体（有分页）
     * @summary 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof FormEntityServicesApi
     */
    public findAll(options?: AxiosRequestConfig) {
        return FormEntityServicesApiFp(this.configuration).findAll(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 作品 id 范围下列出表单实体（有分页）
     * @summary 
     * @param {string} worksId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof FormEntityServicesApi
     */
    public findByWorksId(worksId: string, options?: AxiosRequestConfig) {
        return FormEntityServicesApiFp(this.configuration).findByWorksId(worksId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 找到表单实体
     * @summary 
     * @param {string} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof FormEntityServicesApi
     */
    public findOne(id: string, options?: AxiosRequestConfig) {
        return FormEntityServicesApiFp(this.configuration).findOne(id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 删除表单实体
     * @summary 
     * @param {string} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof FormEntityServicesApi
     */
    public remove(id: string, options?: AxiosRequestConfig) {
        return FormEntityServicesApiFp(this.configuration).remove(id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 更新表单实体
     * @summary 
     * @param {string} id 
     * @param {UpdateFormEntityDto} updateFormEntityDto 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof FormEntityServicesApi
     */
    public update(id: string, updateFormEntityDto: UpdateFormEntityDto, options?: AxiosRequestConfig) {
        return FormEntityServicesApiFp(this.configuration).update(id, updateFormEntityDto, options).then((request) => request(this.axios, this.basePath));
    }
}
