/* tslint:disable */
/* eslint-disable */
/**
 * 表单引擎API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import globalAxios, { AxiosPromise, AxiosInstance, AxiosRequestConfig } from 'axios';
import { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
// @ts-ignore
import { CreateFormResEntity } from '../models';
// @ts-ignore
import { CreateVoteFormDto } from '../models';
/**
 * VoteApi - axios parameter creator
 * @export
 */
export const VoteApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 创建投票组件
         * @summary 
         * @param {CreateVoteFormDto} createVoteFormDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createVoteWidget: async (createVoteFormDto: CreateVoteFormDto, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'createVoteFormDto' is not null or undefined
            assertParamExists('createVoteWidget', 'createVoteFormDto', createVoteFormDto)
            const localVarPath = `/vote/v1/create-vote-widget`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(createVoteFormDto, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        exportList: async (options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/vote/v1/export-list/{formId}`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        exportRankList: async (options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/vote/v1/export-rank/{formId}`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} formId 表单id
         * @param {string} uid 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getRankList: async (formId: string, uid: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'formId' is not null or undefined
            assertParamExists('getRankList', 'formId', formId)
            // verify required parameter 'uid' is not null or undefined
            assertParamExists('getRankList', 'uid', uid)
            const localVarPath = `/vote/v1/rank/{uid}/{formId}`
                .replace(`{${"formId"}}`, encodeURIComponent(String(formId)))
                .replace(`{${"uid"}}`, encodeURIComponent(String(uid)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 投票明细
         * @summary 
         * @param {string} formId 表单id
         * @param {string} uid 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getVoteList: async (formId: string, uid: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'formId' is not null or undefined
            assertParamExists('getVoteList', 'formId', formId)
            // verify required parameter 'uid' is not null or undefined
            assertParamExists('getVoteList', 'uid', uid)
            const localVarPath = `/vote/v1/list/{uid}/{formId}`
                .replace(`{${"formId"}}`, encodeURIComponent(String(formId)))
                .replace(`{${"uid"}}`, encodeURIComponent(String(uid)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 获取投票数据概览
         * @summary 
         * @param {string} worksId 作品ID
         * @param {string} uid 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getVoteOverview: async (worksId: string, uid: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'worksId' is not null or undefined
            assertParamExists('getVoteOverview', 'worksId', worksId)
            // verify required parameter 'uid' is not null or undefined
            assertParamExists('getVoteOverview', 'uid', uid)
            const localVarPath = `/vote/v1/overview/{uid}/{worksId}`
                .replace(`{${"worksId"}}`, encodeURIComponent(String(worksId)))
                .replace(`{${"uid"}}`, encodeURIComponent(String(uid)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * VoteApi - functional programming interface
 * @export
 */
export const VoteApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = VoteApiAxiosParamCreator(configuration)
    return {
        /**
         * 创建投票组件
         * @summary 
         * @param {CreateVoteFormDto} createVoteFormDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async createVoteWidget(createVoteFormDto: CreateVoteFormDto, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<CreateFormResEntity>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.createVoteWidget(createVoteFormDto, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async exportList(options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.exportList(options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async exportRankList(options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.exportRankList(options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @param {string} formId 表单id
         * @param {string} uid 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getRankList(formId: string, uid: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<object>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getRankList(formId, uid, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 投票明细
         * @summary 
         * @param {string} formId 表单id
         * @param {string} uid 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getVoteList(formId: string, uid: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getVoteList(formId, uid, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 获取投票数据概览
         * @summary 
         * @param {string} worksId 作品ID
         * @param {string} uid 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getVoteOverview(worksId: string, uid: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getVoteOverview(worksId, uid, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
    }
};

/**
 * VoteApi - factory interface
 * @export
 */
export const VoteApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = VoteApiFp(configuration)
    return {
        /**
         * 创建投票组件
         * @summary 
         * @param {CreateVoteFormDto} createVoteFormDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createVoteWidget(createVoteFormDto: CreateVoteFormDto, options?: any): AxiosPromise<CreateFormResEntity> {
            return localVarFp.createVoteWidget(createVoteFormDto, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        exportList(options?: any): AxiosPromise<void> {
            return localVarFp.exportList(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        exportRankList(options?: any): AxiosPromise<void> {
            return localVarFp.exportRankList(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {string} formId 表单id
         * @param {string} uid 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getRankList(formId: string, uid: string, options?: any): AxiosPromise<object> {
            return localVarFp.getRankList(formId, uid, options).then((request) => request(axios, basePath));
        },
        /**
         * 投票明细
         * @summary 
         * @param {string} formId 表单id
         * @param {string} uid 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getVoteList(formId: string, uid: string, options?: any): AxiosPromise<void> {
            return localVarFp.getVoteList(formId, uid, options).then((request) => request(axios, basePath));
        },
        /**
         * 获取投票数据概览
         * @summary 
         * @param {string} worksId 作品ID
         * @param {string} uid 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getVoteOverview(worksId: string, uid: string, options?: any): AxiosPromise<void> {
            return localVarFp.getVoteOverview(worksId, uid, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * VoteApi - object-oriented interface
 * @export
 * @class VoteApi
 * @extends {BaseAPI}
 */
export class VoteApi extends BaseAPI {
    /**
     * 创建投票组件
     * @summary 
     * @param {CreateVoteFormDto} createVoteFormDto 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof VoteApi
     */
    public createVoteWidget(createVoteFormDto: CreateVoteFormDto, options?: AxiosRequestConfig) {
        return VoteApiFp(this.configuration).createVoteWidget(createVoteFormDto, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof VoteApi
     */
    public exportList(options?: AxiosRequestConfig) {
        return VoteApiFp(this.configuration).exportList(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof VoteApi
     */
    public exportRankList(options?: AxiosRequestConfig) {
        return VoteApiFp(this.configuration).exportRankList(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {string} formId 表单id
     * @param {string} uid 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof VoteApi
     */
    public getRankList(formId: string, uid: string, options?: AxiosRequestConfig) {
        return VoteApiFp(this.configuration).getRankList(formId, uid, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 投票明细
     * @summary 
     * @param {string} formId 表单id
     * @param {string} uid 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof VoteApi
     */
    public getVoteList(formId: string, uid: string, options?: AxiosRequestConfig) {
        return VoteApiFp(this.configuration).getVoteList(formId, uid, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 获取投票数据概览
     * @summary 
     * @param {string} worksId 作品ID
     * @param {string} uid 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof VoteApi
     */
    public getVoteOverview(worksId: string, uid: string, options?: AxiosRequestConfig) {
        return VoteApiFp(this.configuration).getVoteOverview(worksId, uid, options).then((request) => request(this.axios, this.basePath));
    }
}
