import { CopyRowData } from '../../shared';
export const addPictureDataFor2Pic = {
  rows: [
    {
      id: 'YpDGJlHEft',
      cells: [],
      childrenIds: [],
      children: [
        {
          id: 'BzcwQmelMb',
          cells: [],
          childrenIds: ['wvBhGDirnk'],
          children: [],
          style: {
            display: 'flex',
            flexDirection: 'column',
            flex: 1,
            gridTemplateColumns: '1fr',
            writingMode: 'horizontal-tb',
            alignSelf: 'unset',
            justifySelf: 'unset',
            placeSelf: 'unset',
            minHeight: 'auto',
            zIndex: 2,
            gridTemplateRows: 'unset',
            gap: '12px',
          },
        },
        {
          id: 'MZaiMpohaN',
          cells: [],
          childrenIds: ['nGwXzwHeD_'],
          children: [],
          style: {
            display: 'flex',
            flexDirection: 'column',
            flex: 1,
            gridTemplateColumns: '1fr',
            writingMode: 'horizontal-tb',
            alignSelf: 'unset',
            justifySelf: 'unset',
            placeSelf: 'unset',
            minHeight: 'auto',
            zIndex: 2,
            gridTemplateRows: 'unset',
            gap: '12px',
          },
          parentRowIds: [
            'aeqYNYTywv',
            'SFluTWRPPv',
            'wXAEgakNTE',
            'YpDGJlHEft',
            'MZaiMpohaN',
          ],
          depth: [1, 2, 1, 0, 1],
        },
      ],
      style: {
        display: 'flex',
        flexDirection: 'row',
        flex: 1,
        gridTemplateColumns: '1fr',
        writingMode: 'horizontal-tb',
        alignSelf: 'unset',
        justifySelf: 'unset',
        placeSelf: 'unset',
        minHeight: 'auto',
        zIndex: 2,
        gridTemplateRows: 'unset',
        gap: '12.00px',
      },
      sourceRowId: 'FmnAtkRFvC',
    },
  ],
  elemComps: [
    {
      elementRef: 'Picture',
      attrs: {
        ossPath:
          'https://img2.maka.im/cdn/jiantie/works-resources/605056689/98238269209542_063cf7.png?x-oss-process=image%2Fformat%2Cwebp',
        aspectRatio: 0.75,
        originBaseW: 1200,
        originBaseH: 1600,
        version: 2,
        _v: 4,
        disabledToEdit: false,
      },
      elemId: 'wvBhGDirnk',
      type: 'element',
    },
    {
      elementRef: 'Picture',
      attrs: {
        ossPath:
          'https://img2.maka.im/cdn/jiantie/works-resources/605056689/98238269209542_063cf7.png?x-oss-process=image%2Fformat%2Cwebp',
        aspectRatio: 0.75,
        originBaseW: 1200,
        originBaseH: 1600,
        version: 2,
        _v: 4,
        disabledToEdit: false,
      },
      elemId: 'nGwXzwHeD_',
      type: 'element',
    },
  ],
  positionLink: {
    wvBhGDirnk: {
      lock: true,
      visibility: false,
      rotate: 0,
      opacity: 1,
      zIndex: 105389,
      mount: false,
      x: 0,
      y: 0,
      tag: 'photo1',
      disabled: true,
    },
    nGwXzwHeD_: {
      lock: true,
      visibility: false,
      rotate: 0,
      opacity: 1,
      zIndex: 105389,
      mount: false,
      x: 0,
      y: 0,
      disabled: true,
      tag: 'photo1',
    },
  },
} as CopyRowData;
