export const defaultWorksData: any = {
  _version: 18,
  pageSetting: {
    paginAnimateSetting: {
      autoPlay: false,
      indicator: 'slim',
      pageNumber: 'none',
      pageTurningEffect: 'layer',
      autoPlayTime: 3,
      disableManualPageTurning: false,
    },
  },
  canvasData: {
    width: 375,
    height: 45,
    visualHeight: 45,
    content: {
      pages: [
        {
          layers: [
            {
              attrs: {
                style: {},
                tag: 'head_card',
                originBoxInfo: {
                  width: 'auto',
                  height: 'auto',
                },
                textScale: 1,
                fontSize: 55,
                gridsData: [
                  {
                    id: 'aHNnHKPotu',
                    tag: 'block',
                    cells: [],
                    style: {
                      gap: '0px',
                      flex: 1,
                      width: 'auto',
                      rowGap: 0,
                      display: 'flex',
                      columnGap: 0,
                      minHeight: 48,
                      flexDirection: 'column',
                    },
                    children: [
                      {
                        id: 'BZmYGDNYwx',
                        tag: 'grid_root',
                        cells: [],
                        style: {
                          gap: 8,
                          flex: 1,
                          display: 'flex',
                          minHeight: 48,
                          alignItems: 'center',
                          flexDirection: 'row',
                          justifyContent: 'flex-start',
                        },
                        childrenIds: ['nwBiErRdFg', '_lCARHksFE'],
                        isRepeatList: false,
                        parentRowIds: [
                          'xoYmnmiQsX',
                          'mKygZmnem_',
                          'aYzBnCihAY',
                        ],
                      },
                    ],
                    childrenIds: [],
                    groupByRowId: 'ZvgSKnxJqb',
                    isRepeatList: false,
                    parentRowIds: ['aHNnHKPotu'],
                  },
                ],
                version: 'v2.1',
                themeConfig2: {
                  text_free: {},
                  text_heading1: {
                    fontSize: 32,
                    lineHeight: 1.2,
                    letterSpacing: 0,
                  },
                  text_heading2: {
                    fontSize: 24,
                    lineHeight: 1.3,
                    letterSpacing: 0,
                  },
                  text_heading3: {
                    fontSize: 20,
                    lineHeight: 1.4,
                    letterSpacing: 0,
                  },
                  text_body: {
                    fontSize: 16,
                    lineHeight: 1.5,
                    letterSpacing: 0,
                  },
                  text_desc: {
                    fontSize: 14,
                    lineHeight: 1.4,
                    letterSpacing: 0,
                  },
                  photo1: {},
                  photo2: {},
                  photo3: {},
                  photo4: {},
                  block: {},
                  grid_root: {},
                  grid_root_head: {},
                  grid_root_content: {},
                  grid_root_footer: {},
                  grid_cell_root: {},
                  grid_cell_2: {},
                  list_root: {},
                  list_cell_root: {},
                  page: {},
                  grid_main: {},
                  grid_sub: {},
                  grid_strong: {},
                  grid_info: {},
                  grid_free: {},
                  themeColors: [],
                },
                _updateVersion: 87,
                cmsSetting: {},
                stylePackV2: {
                  name: '未保存风格',
                  documentId: '',
                  author: '',
                  desc: '',
                  cover_url: '',
                },
                themePackV2: {
                  name: '三级分类',
                },
                _v: null,
              },
              elementRef: 'GridV3',
              elemId: 'YNhZyvRJEf',
              type: 'element',
            },
            {
              type: 'element',
              attrs: {
                crop: false,
                baseH: 300,
                baseW: 300,
                rotate: 0,
                ossPath:
                  'https://res.maka.im/cdn/jiantie/works-resources/605294846/98243139626260_d97f9f.png',
                layoutStyle: {
                  width: 'auto',
                  height: 45,
                },
                originBaseH: 300,
                originBaseW: 300,
                strokeStyle: [],
                disabledToEdit: false,
                flipHorizontal: false,
                objectPosition: {
                  x: 50,
                  y: 50,
                  size: 'contain',
                  zoom: 1,
                },
                aspectRatio: 1,
                version: 2,
              },
              elemId: 'nwBiErRdFg',
              elementRef: 'Picture',
            },
            {
              type: 'element',
              attrs: {
                text: 'XXX公司',
                fontUrl:
                  'https://font.maka.im/20190724/Alibaba-PuHuiTi-Bold.ttf',
                fontFamily: 'Alibaba-PuHuiTi-Bold',
                lineHeight: 1.5,
              },
              elemId: '_lCARHksFE',
              elementRef: 'Text',
            },
          ],
          opacity: 1,
          background: {
            materialId: '',
            bgpic: '',
            bgcolor: '',
            colors: null,
            bgpictype: '',
            bgpicwidth: 375,
            bgpicleft: 0,
            bgpictop: 0,
            atmosphere: {
              url: '',
            },
            bgpicheight: 352,
            canvaswidth: 375,
            canvasheight: 352,
            originwidth: 750,
            originheight: 684,
            bgpicscalerate: 1,
            opacity: 1,
          },
          id: 'zCuwybEoZy',
          width: 375,
          height: 45,
          options: {
            height: 300,
            enableCopy: false,
            enableUserTransformHeight: false,
            disabledPageOptions: true,
          },
          pageIndex: 1,
        },
      ],
      fixedPages: {
        layers: [],
      },
      fixedLayer: [],
    },
    actions: {},
    music: {
      title: '',
      materialId: '',
      duration: 0,
      url: '',
      preview: '',
    },
    __unitProcessed: 9,
  },
  positionLink: {
    YNhZyvRJEf: {
      lock: false,
      visibility: true,
      rotate: 0,
      borderRadius: 0,
      opacity: 1,
      zIndex: 0,
      mount: true,
      x: 0,
      y: 0,
      width: 375,
      height: 162.3984375,
    },
    nwBiErRdFg: {
      x: 0,
      y: 0,
      tag: 'photo4',
      lock: true,
      mount: false,
      rotate: 0,
      zIndex: 105043,
      opacity: 1,
      disabled: true,
      visibility: false,
      borderRadius: 0,
    },
    _lCARHksFE: {
      x: 0,
      y: 0,
      tag: 'text_free',
      lock: true,
      mount: false,
      rotate: 0,
      zIndex: 105044,
      opacity: 1,
      disabled: true,
      visibility: false,
      borderRadius: 0,
    },
  },
  meta: {
    originCanvasScale: {
      width: 375,
      height: 738,
    },
  },
  style: {
    themeSchema: {},
    themeConfig: {
      titleVisible: false,
      avatar: {
        alignment: 'left',
        visible: false,
      },
      time: {
        type: 'create_time',
        visible: false,
      },
      readCountVisible: false,
    },
  },
};
