export const defaultWorksData: any = {
  isGridMode: true,
  gridProps: {
    style: {},
    tag: 'head_card',
    gridsData: [
      {
        id: 'aHNnHKPotu',
        tag: 'block',
        cells: [],
        style: {
          gap: '0px',
          flex: 1,
          width: 'auto',
          rowGap: 0,
          display: 'flex',
          columnGap: 0,
          minHeight: 48,
          flexDirection: 'column',
        },
        children: [
          {
            id: 'BZmYGDNYwx',
            tag: 'grid_root',
            cells: [],
            style: {
              gap: 8,
              flex: 1,
              display: 'flex',
              minHeight: 48,
              alignItems: 'center',
              flexDirection: 'row',
              justifyContent: 'flex-start',
            },
            childrenIds: ['nwBiErRdFg', '_lCARHksFE'],
            isRepeatList: false,
          },
        ],
        childrenIds: [],
        groupByRowId: 'ZvgSKnxJqb',
        isRepeatList: false,
      },
    ],
    version: 'v2.1',
    _updateVersion: 87,
    id: 'YNhZyvRJEf',
  },
  layersMap: {
    nwBiErRdFg: {
      type: 'element',
      attrs: {
        crop: false,
        baseH: 300,
        baseW: 300,
        rotate: 0,
        ossPath:
          'https://res.maka.im/cdn/jiantie/works-resources/605294846/98243139626260_d97f9f.png',
        layoutStyle: {
          width: 'auto',
          height: 45,
        },
        originBaseH: 300,
        originBaseW: 300,
        strokeStyle: [],
        disabledToEdit: false,
        flipHorizontal: false,
        objectPosition: {
          x: 50,
          y: 50,
          size: 'contain',
          zoom: 1,
        },
        aspectRatio: 1,
        version: 2,
      },
      elemId: 'nwBiErRdFg',
      elementRef: 'Picture',
      tag: 'photo4',
    },
    _lCARHksFE: {
      type: 'element',
      attrs: {
        text: 'XXX公司',
        fontUrl: 'https://font.maka.im/20190724/Alibaba-PuHuiTi-Bold.ttf',
        fontFamily: 'Alibaba-PuHuiTi-Bold',
        lineHeight: 1.5,
      },
      elemId: '_lCARHksFE',
      tag: 'text_free',
      elementRef: 'Text',
    },
  },
  music: {
    title: '',
    materialId: '',
    duration: 0,
    url: '',
    preview: '',
  },
  _version: 18,
};
